// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: records/records.proto

package records

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command_Op int32

const (
	Command_NONE    Command_Op = 0
	Command_GETDB   Command_Op = 1
	Command_GETFILE Command_Op = 2
)

// Enum value maps for Command_Op.
var (
	Command_Op_name = map[int32]string{
		0: "NONE",
		1: "GETDB",
		2: "GETFILE",
	}
	Command_Op_value = map[string]int32{
		"NONE":    0,
		"GETDB":   1,
		"GETFILE": 2,
	}
)

func (x Command_Op) Enum() *Command_Op {
	p := new(Command_Op)
	*p = x
	return p
}

func (x Command_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_records_records_proto_enumTypes[0].Descriptor()
}

func (Command_Op) Type() protoreflect.EnumType {
	return &file_records_records_proto_enumTypes[0]
}

func (x Command_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Op.Descriptor instead.
func (Command_Op) EnumDescriptor() ([]byte, []int) {
	return file_records_records_proto_rawDescGZIP(), []int{3, 0}
}

type Dir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TimeNs int64  `protobuf:"fixed64,2,opt,name=timeNs,proto3" json:"timeNs,omitempty"`
}

func (x *Dir) Reset() {
	*x = Dir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_records_records_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir) ProtoMessage() {}

func (x *Dir) ProtoReflect() protoreflect.Message {
	mi := &file_records_records_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir.ProtoReflect.Descriptor instead.
func (*Dir) Descriptor() ([]byte, []int) {
	return file_records_records_proto_rawDescGZIP(), []int{0}
}

func (x *Dir) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Dir) GetTimeNs() int64 {
	if x != nil {
		return x.TimeNs
	}
	return 0
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DirIndex int64  `protobuf:"varint,2,opt,name=dirIndex,proto3" json:"dirIndex,omitempty"`
	Hash     []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	TimeNs   int64  `protobuf:"fixed64,4,opt,name=timeNs,proto3" json:"timeNs,omitempty"`
	Size     int64  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_records_records_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_records_records_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_records_records_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetDirIndex() int64 {
	if x != nil {
		return x.DirIndex
	}
	return 0
}

func (x *File) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *File) GetTimeNs() int64 {
	if x != nil {
		return x.TimeNs
	}
	return 0
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DbHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DirCount  int64 `protobuf:"varint,1,opt,name=dirCount,proto3" json:"dirCount,omitempty"`
	FileCount int64 `protobuf:"varint,2,opt,name=fileCount,proto3" json:"fileCount,omitempty"`
}

func (x *DbHeader) Reset() {
	*x = DbHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_records_records_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DbHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbHeader) ProtoMessage() {}

func (x *DbHeader) ProtoReflect() protoreflect.Message {
	mi := &file_records_records_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbHeader.ProtoReflect.Descriptor instead.
func (*DbHeader) Descriptor() ([]byte, []int) {
	return file_records_records_proto_rawDescGZIP(), []int{2}
}

func (x *DbHeader) GetDirCount() int64 {
	if x != nil {
		return x.DirCount
	}
	return 0
}

func (x *DbHeader) GetFileCount() int64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op   Command_Op `protobuf:"varint,1,opt,name=op,proto3,enum=Command_Op" json:"op,omitempty"`
	Hash []byte     `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_records_records_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_records_records_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_records_records_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetOp() Command_Op {
	if x != nil {
		return x.Op
	}
	return Command_NONE
}

func (x *Command) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type CacheMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TimeNs int64  `protobuf:"fixed64,2,opt,name=timeNs,proto3" json:"timeNs,omitempty"`
	Device uint64 `protobuf:"varint,3,opt,name=device,proto3" json:"device,omitempty"`
}

func (x *CacheMeta) Reset() {
	*x = CacheMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_records_records_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheMeta) ProtoMessage() {}

func (x *CacheMeta) ProtoReflect() protoreflect.Message {
	mi := &file_records_records_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheMeta.ProtoReflect.Descriptor instead.
func (*CacheMeta) Descriptor() ([]byte, []int) {
	return file_records_records_proto_rawDescGZIP(), []int{4}
}

func (x *CacheMeta) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CacheMeta) GetTimeNs() int64 {
	if x != nil {
		return x.TimeNs
	}
	return 0
}

func (x *CacheMeta) GetDevice() uint64 {
	if x != nil {
		return x.Device
	}
	return 0
}

var File_records_records_proto protoreflect.FileDescriptor

var file_records_records_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x03, 0x44, 0x69, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x10, 0x52, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x73, 0x22, 0x76, 0x0a, 0x04, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x72, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x69, 0x72, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x10, 0x52, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x22, 0x44, 0x0a, 0x08, 0x44, 0x62, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x69, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x64, 0x69, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69,
	0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x62, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0b, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x22, 0x26, 0x0a, 0x02, 0x4f, 0x70, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x45, 0x54, 0x44, 0x42, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x47, 0x45, 0x54, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x02, 0x22, 0x4f, 0x0a, 0x09,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x10, 0x52, 0x06, 0x74,
	0x69, 0x6d, 0x65, 0x4e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42, 0x25, 0x5a,
	0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_records_records_proto_rawDescOnce sync.Once
	file_records_records_proto_rawDescData = file_records_records_proto_rawDesc
)

func file_records_records_proto_rawDescGZIP() []byte {
	file_records_records_proto_rawDescOnce.Do(func() {
		file_records_records_proto_rawDescData = protoimpl.X.CompressGZIP(file_records_records_proto_rawDescData)
	})
	return file_records_records_proto_rawDescData
}

var file_records_records_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_records_records_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_records_records_proto_goTypes = []interface{}{
	(Command_Op)(0),   // 0: Command.Op
	(*Dir)(nil),       // 1: Dir
	(*File)(nil),      // 2: File
	(*DbHeader)(nil),  // 3: DbHeader
	(*Command)(nil),   // 4: Command
	(*CacheMeta)(nil), // 5: CacheMeta
}
var file_records_records_proto_depIdxs = []int32{
	0, // 0: Command.op:type_name -> Command.Op
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_records_records_proto_init() }
func file_records_records_proto_init() {
	if File_records_records_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_records_records_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_records_records_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_records_records_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DbHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_records_records_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_records_records_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_records_records_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_records_records_proto_goTypes,
		DependencyIndexes: file_records_records_proto_depIdxs,
		EnumInfos:         file_records_records_proto_enumTypes,
		MessageInfos:      file_records_records_proto_msgTypes,
	}.Build()
	File_records_records_proto = out.File
	file_records_records_proto_rawDesc = nil
	file_records_records_proto_goTypes = nil
	file_records_records_proto_depIdxs = nil
}
